### ISSUE TITLE
Defining Fog::Google::Compute instead of Fog::Compute::Google

### ISSUE THREAD

**Issue by apuntamb** [fog/fog-google#497] opened 2020-05-21 08:24 UTC
Hello @Temikus !
I checked with multiple fog provider plugins and the definition they use is a common one for eg. `Fog::Provider::Compute` and not `Fog::Compute::Provider`. Please refer to this [issue](https://github.com/fog/fog-aws/issues/565#issuecomment-631660289) in fog-aws for more details as to why it would be a better choice to change this.
Let me know if you need any more information on this.

**Comment by Temikus** [comment] 2020-06-27 01:45
Yeah, we're planning on it, see https://github.com/fog/fog-google/pull/422

But the problem is that it's a large breaking change as I don't see an easy way to alias namespaces so they're forward compatible and requires extensive testing. As this is a purely free-time project, I sadly don't have the bandwidth to do it yet.

**Comment by Temikus** [comment] 2020-06-27 01:45
I'll close this as a dup, but feel free to reopen if I'm missing something. ( Or you would like to contribute :) )

**Closed by Temikus** 2020-06-27 01:45 UTC
