### ISSUE TITLE
Relax fog-core dependency version

### ISSUE THREAD

**Issue by utkarsh2102** [fog/fog-google#438] opened 2019-01-24 00:13 UTC
`fog-core` has their latest version out, that is 2.1.2.
However, the following line isn't allowing to update `fog-core`.

https://github.com/fog/fog-google/blob/f5202c20d183c077dc370d0c9cd2f90311b984ec/fog-google.gemspec#L24

Can the same be relaxed?

**Comment by Temikus** [comment] 2020-07-22 02:15
Duplicate of #421

**Closed by Temikus** 2020-07-22 02:15 UTC
