### ISSUE TITLE
Exception raised in #get_target_pool_health when instance is terminated

### ISSUE THREAD

**Issue by plribeiro3000** [fog/fog-google#41] opened 2015-05-31 04:16 UTC
Google instances can be terminated, yet still in a Target Pool.  A `Fog::Errors::Error` exception is raised as 'resource is not ready', which prevents you from getting health for all other instances in that Target Pool.

Here's how I'm calling Target Pool `#get_health`

```
  if (t = load_balancers.target_pools.get(n)) && t.get_health.any?
          Hash[*t.get_health.map{|i, h|
                 i = i.split_link if split
                 [i, {:state => h.first['healthState'], :ip_address => h.first['ipAddress'] }]
               }.flatten]
  end
```

And the backtrace

```
#<Fog::Errors::Error: The resource 'projects/<PROJECT>/zones/us-central1-b/instances/<INSTANCE>' is not ready>
/Users/dacamp/.rvm/gems/ruby-2.0.0-p481/gems/fog-1.23.0/lib/fog/google/compute.rb:179:in `build_excon_response'
/Users/dacamp/.rvm/gems/ruby-2.0.0-p481/gems/fog-1.23.0/lib/fog/google/compute.rb:959:in `build_response'
/Users/dacamp/.rvm/gems/ruby-2.0.0-p481/gems/fog-1.23.0/lib/fog/google/requests/compute/get_target_pool_health.rb:21:in `block in get_target_pool_health'
/Users/dacamp/.rvm/gems/ruby-2.0.0-p481/gems/fog-1.23.0/lib/fog/google/requests/compute/get_target_pool_health.rb:19:in `map'
/Users/dacamp/.rvm/gems/ruby-2.0.0-p481/gems/fog-1.23.0/lib/fog/google/requests/compute/get_target_pool_health.rb:19:in `get_target_pool_health'
/Users/dacamp/.rvm/gems/ruby-2.0.0-p481/gems/fog-1.23.0/lib/fog/google/models/compute/target_pool.rb:79:in `get_health'
```

**Comment by plribeiro3000** [comment] 2015-05-31 04:18
The original issue was reported by @dacamp at fog/fog#3114.

cc/ @dacamp @icco @geemus

**Comment by bpaquet** [comment] 2016-07-26 21:15
This patch can help.
https://github.com/Madgic/fog-google/commit/b28365506918a3ad2ef0a43336fcaa9e7a75d7ea

**Comment by icco** [comment] 2016-07-27 00:00
https://github.com/fog/fog-google/compare/master...Madgic:master

**Comment by bpaquet** [comment] 2016-07-27 13:33
The fix I did just catch any error to return nil for instance in error. I can do a proper PR if you think it's a good solution.

**Comment by geemus** [comment] 2016-07-27 17:03
@icco @Temikus thoughts?

**Comment by icco** [comment] 2016-07-27 17:42
Seems like a reasonable solution, although I wish Google had an API that returned a hash with all the health data.

**Comment by geemus** [comment] 2016-07-27 18:56
Agreed. @bpaquet sounds like a proper PR would be great. Thanks!

**Comment by Temikus** [comment] 2016-07-27 21:03
Ok, 2 separate things:
- I'm generally not a fan of using try-catch instead of proper logic. Is it possible to get request status without it throwing an exception and branch on that? Though I think we can use that as an interim solution, however, the catch-all `rescue` will need to at least specify the exception class, otherwise we may rescue things we really don't want to ignore.

- The backend behaviour seems weird to me, there should be no hard-terminated instances in target pools in the first place. I'll investigate...

**Comment by Temikus** [comment] 2018-05-27 05:08
This was fixed on the backend a while ago. Apologies for forgetting to close out the issue.

**Comment by Temikus** [comment] 2018-05-27 05:08
Stopped instances now return 'UNHEALTHY' status properly.

**Comment by bpaquet** [comment] 2018-05-27 15:03
I still can not use get_health, I have to call get_health(x) on instance which really exists.

**Comment by Temikus** [comment] 2018-05-27 22:46
@bpaquet - ok, that’s bad, sorry about that.

 I’ve just tested with stopped instances and it did work. I did notice that resource may intermittently return NotReady while the health check is established, I’m digging into that and if I cannot get this resolved quickly i’ll wrap the call to back off on NotReady.

Can you reproduce? If so - what’s the logic you’re following?

I’ll reopen because this needs to be fixed.

**Closed** 2021-04-25 02:34 UTC
Labels: bug, hacktoberfest, help wanted, no-issue-activity, priority/medium
