### ISSUE TITLE
Error in Ruby's rescue clause

### ISSUE THREAD

**Issue by mouchtaris** [fog/fog-google#20] opened 2015-04-21 11:48 UTC
In the following file/commit/line:

https://github.com/fog/fog-google/commit/1976f5c62027042311809e5d17de36bfec833dcb#commitcomment-10822546

Causes (at least) the following error:

    /.../ruby/2.2.0/gems/fog-google-0.0.3/lib/fog/google/models/compute/images.rb:67:in `rescue in get': class or module required for rescue clause (TypeError)
        from /.../ruby/2.2.0/gems/fog-google-0.0.3/lib/fog/google/models/compute/images.rb:47:in `get'
        from /.../ruby/2.2.0/gems/fog-google-0.0.3/lib/fog/google/requests/compute/insert_disk.rb:77:in `insert_disk'
        from /.../ruby/2.2.0/gems/fog-google-0.0.3/lib/fog/google/models/compute/disk.rb:40:in `save'
        from /.../ruby/2.2.0/gems/fog-core-1.30.0/lib/fog/core/collection.rb:51:in `create'
        from ...

**Comment by plribeiro3000** [comment] 2015-04-21 11:57
@mouchtaris Thank you for your feedback!

@ihmccreery Perhaps you want to check this out?

**Comment by ihmccreery** [comment] 2015-04-21 14:27
Hi @mouchtaris.  Sorry you're having trouble.  We're having a bit of a bumpy ride as we move things around in Fog.

Can you give more context about how this came up?  What code did you try to execute that gave you this error, so I can try to reproduce it?  It looks like you were trying to create a disk.  What `requires` did you use?

**Comment by mouchtaris** [comment] 2015-04-21 15:32
Hello.

Regardless of the conditions that reproduce this error, this code fragment is invalid Ruby code, and in fact it is not a simple typo. The original purpose of the author is completely unclear, and I think it should be made clear what this code is supposed to do in case of some error before testing how it actually behaves with it.

Nevertheless, for me the error is easily reproducible if I pass a `Fixnum` value for the `source_image` parameter. 

    google_client = Google::APIClient.new(
      application_name: 'app_name',
      application_version: 'app_version',
      ).tap { |client|
        client.authorization = :google_app_default
        client.authorization.fetch_access_token!
      }

    Fog::Compute::Google.new(
      google_client: google_client,
      google_project: 'project'
      ).disks.create zone: 'europe-west1-c', name: 'disk', size_gb: 10, source_image: 1200

    => TypeError: class or module required for rescue clause
    from /.../ruby/2.2.0/gems/fog-google-0.0.3/lib/fog/google/models/compute/images.rb:67:in `rescue in get'

**Comment by mouchtaris** [comment] 2015-04-21 15:33
I am available for any other enquiry.

**Comment by ihmccreery** [comment] 2015-04-21 15:45
Thanks for the spot & explanation @mouchtaris; I didn't originally see that it didn't have a `begin` clause.

It looks like this originally made its way into the codebase in fog/fog@39188c331cbe5e51169f5dcd12694a998f5502ba.

I'm continuing my investigation for a fix, but I thought I'd pass along that information at least, since @mouchtaris was wondering what the intent was.

**Comment by ihmccreery** [comment] 2015-04-21 16:21
Okay, I've reproduced the bug.

Reverting that block of code to [the parent commit](https://github.com/fog/fog/blob/bf46f69fe92605b017873fc9424d8bbf46b5aa50/lib/fog/google/models/compute/images.rb) fixes it???, but, somewhat unrelatedly, the `images` functionality is currently broken regardless, as [the API](https://cloud.google.com/compute/docs/reference/latest/images#resource) has changed, but the codebase hasn't reflected that change.  I actually started working on the fix yesterday, but haven't finished yet.

With the reversion, @mouchtaris's code will now give the following:

```
ArgumentError: Parameter 'image' has an invalid value: 1200. Must match: /^[a-z](?:[-a-z0-9]{0,61}[a-z0-9])?$/.
```

I will continue work on fixing images to work with the API.

**Comment by ihmccreery** [comment] 2015-04-21 16:52
The desired functionality is: if we can't find the disk, it should return `nil`, not raise an error, so I've gone ahead and changed it.  The note above about it being broken due to API changes still applies, unfortunately.  I will try to get that fixed by the end of the day today.

**Closed** 2015-04-21 17:13 UTC
Labels: bug, priority/high

**Comment by ihmccreery** [comment] 2015-04-21 22:28
Correction: the current implementation is *not* broken.  See #22 for updates.
