### ISSUE TITLE
Issue Implementing Fog::Google with GKE Workload Identity

### ISSUE THREAD

**Issue by chvreddy** [fog/fog-google#502] opened 2020-07-27 02:01 UTC
I am Having issue Downloading files from **GCS** IN **GKE** with **WorkLoad Identity** Feature enabled.

Downloading files is working fine when we are using Service account credentials, later suggested by google that Workload Identity is the best option to use in **GKE** we shifted from using **Service accounts credentials ** to **Workload identity** feature.

But the download is not working. Below is the error:

```
TypeError: no implicit conversion of nil into String
        from /bundle/gems/fog-google-1.10.0/lib/fog/storage/google_json/real.rb:62:in `initialize'
        from /bundle/gems/fog-google-1.10.0/lib/fog/storage/google_json/real.rb:62:in `new'
        from /bundle/gems/fog-google-1.10.0/lib/fog/storage/google_json/real.rb:62:in `signature'
        from /bundle/gems/fog-google-1.10.0/lib/fog/storage/google_json/utils.rb:31:in `host_path_query'
        from /bundle/gems/fog-google-1.10.0/lib/fog/storage/google_json/utils.rb:10:in `https_url'
        from /bundle/gems/fog-google-1.10.0/lib/fog/storage/google_json/requests/get_object_https_url.rb:9:in `get_object_https_url'
        from /bundle/gems/fog-google-1.10.0/lib/fog/storage/google_json/models/files.rb:45:in `get_https_url'
        from /bundle/gems/paperclip-5.3.0/lib/paperclip/storage/fog.rb:156:in `public_send'
        from /bundle/gems/paperclip-5.3.0/lib/paperclip/storage/fog.rb:156:in `expiring_url'`

```

Any work around/permanent code fix to make downloading work with Workload identity feature

**Comment by frankyn** [comment] 2020-07-29 21:55
Hi @chvreddy, could you provide an example that reproduces this issue?

**Comment by chvreddy** [comment] 2020-07-29 22:54
@frankyn here we are trying download a PDF file from GCS using paper clip attachment using fog::google
first we implemented that using 
```
Paperclip::Attachment.default_options[:fog_credentials] = {
    provider: 'Google',
    google_project: ENV['GCS_PROJECT'],
    google_json_key_string: ENV['GCS_CREDENTIALS']  #todo: remove this line when Workload identity is enabled for uploading docs(by creating signed URl's)
  }
```
later we removed google_json_key_string: ENV['GCS_CREDENTIALS'] as we moved to workload identity feature hence got the above error.
please let me know if you need any further details.

**Comment by frankyn** [comment] 2020-07-29 23:07
Thanks @chvreddy,

Could you include how you generate the signed URL download as well?

**Comment by chvreddy** [comment] 2020-07-30 00:12
@frankyn  below is the method we used to Download image
```def render_gcs_url(doc, attachment_name=:attachment)
      klass = doc.class.name
      attachment = doc.send(attachment_name)(return value will be paperclip attachment)`
      redirect_to attachment.expiring_url(GCS_URL_EXPIRE_IN_SECONDS).to_s```

**Comment by frankyn** [comment] 2020-07-30 16:30
@Temikus is this something us with?

In google-cloud-storage we needed to introduce a new pattern which allows providing a signer used to generate Signed URL signatures in environments like GKE, GCE, GCF.

Issue: https://github.com/googleapis/google-cloud-ruby/issues/6268
PR: https://github.com/googleapis/google-cloud-ruby/pull/7091

Update was released in version 1.27.0 google-cloud-storage gem.

**Comment by Temikus** [comment] 2020-07-30 22:13
@frankyn I should be able to help with this, but sometime next week. I’m still in recovery after surgery ATM.

If you need something to be addressed faster than that @icco may be able to help.

**Comment by frankyn** [comment] 2020-07-31 17:45
Thanks @Temikus (hope you feel better soon!)

Next week sounds good to me. Thank you!

**Comment by Temikus** [comment] 2020-08-07 03:49
Alright, I'm back. So, looking at this, it will require a non-trivial amount of effort as Fog uses `google-api-client` gem, so we'll have to reimplement your code in `google-cloud-storage`, essentially :| 

@frankyn - if I'm reading your PR right, we're still signing the headers, just using the new IAM SignServiceAccountBlob API. Is that a correct assessment?

For context, here's the current signature logic used for signed urls: 
https://github.com/fog/fog-google/blob/42b8df5bd2da9edf0a4a1e6574f69a069bdedec1/lib/fog/storage/google_json/real.rb#L25
https://github.com/fog/fog-google/blob/574dce164a69af46542cc4714490ecaab7c79230/lib/fog/storage/google_json/utils.rb#L20

**Comment by frankyn** [comment] 2020-08-07 20:02
Thanks @Temikus!

The main change is to allow for signature to be provided by IAM SignServiceAccountBlob API. You wouldn't need to re-implement the code in google-cloud-storage entirely. I see fog only uses v2 Signed URLs while google-cloud-storage uses V2 and V4.

I was expecting a parameter to swap out the following logic with a lambda:
https://github.com/fog/fog-google/blob/42b8df5bd2da9edf0a4a1e6574f69a069bdedec1/lib/fog/storage/google_json/real.rb#L59-L61

May something like:
```ruby
# Wrap existing signer into a helper method
def default_signer signing_key
          key = OpenSSL::PKey::RSA.new(signing_key)
          digest = OpenSSL::Digest::SHA256.new
          signed_string = key.sign(digest, string_to_sign)
end
```

Then:
```ruby
# custom_signer is a parameter passed in as an option. 
signed_string = nil
if custom_signer.is_a? Proc
  signed_string = custom_signer(string_to_sign)
else
  signed_string = default_signer(string_to_sign)  
end
Base64.encode64(signed_string).chomp!
```

It should be possible to pass in GoogleAccessId as well, but should be more lightweight than this change.

**Comment by Temikus** [comment] 2020-08-11 00:34
@frankyn Thanks Frank! I now know what to do. The lambda path will not likely work here though as that'll require to modify `paperclip` which is no longer under active development AFAIK. So I will have to detect if we're using GCE credentials (`::Google::Auth::GCECredentials.on_gce?`) and try to fall back on those if possible.

This will take a bit more though as due to https://github.com/googleapis/google-auth-library-ruby/issues/270 I will have to implement my own metadata logic.

**Comment by Temikus** [comment] 2020-08-11 04:19
Hm, trying to simulate this I'm getting `Google::Apis::ClientError: forbidden: The caller does not have permission`, even though I auth with the correct scopes:
```
[17] pry(#<Fog::Storage::GoogleJSON::Real>)> iam_client.authorization = ::Google::Auth.get_application_default scopes
=> #<Google::Auth::GCECredentials:0x0000560362c118b0
...
 @scope=["https://www.googleapis.com/auth/devstorage.full_control", "https://www.googleapis.com/auth/iam"],
```
And the service account for the instance has both owner and token creator roles.

@frankyn If you don't mind I might ping you tomorrow morning to try and get to the bottom of it.

**Comment by Temikus** [comment] 2020-08-11 10:11
@chvreddy - I've put a PR into staging: #503 
Can you try it out and see if it works in your environment? Just `bundle` it from git or `rake build` for a local gem.

@frankyn Thanks a bunch for the pointers Frank, really appreciated!

**Comment by chvreddy** [comment] 2020-08-11 16:25
sure @Temikus will let you know once we try it out.

**Comment by chvreddy** [comment] 2020-08-12 03:54
@Temikus tried the fix and everything works perfectly, Thanks for the fix. Can we expect this fix to release soon If it takes time will bundle this release version in git.

**Closed** 2020-08-13 00:39 UTC
Labels: enhancement, priority/high

**Comment by Temikus** [comment] 2020-08-13 00:43
@chvreddy Sweet! I'll push out a release shortly.
