### ISSUE TITLE
% symbol in marker filename causes 403 error

### ISSUE THREAD

**Issue by yanismydj** [fog/fog-google#471] opened 2019-09-23 20:27 UTC
Kind of a crazy scenario, but I've run into it a few times now.
This is using the `Fog::Storage::GoogleXML` class.

Steps to reproduce:
1. Create a file in a google cloud bucket with any name that includes a `%` symbol.  This is a valid filename in google storage.
ie: `filename_with_%_etc.json`
2. use the `.files.all` method, include a param `marker` set to the filename with `%` in it
ie: 
```ruby
GoogleCloud.directories.get("bucket-name").files.all(marker: "filename_with_%_etc.json")`
```

you'll get back an error message as follows:
```ruby
Traceback (most recent call last):
        1: from (irb):1
Excon::Error::Forbidden (Expected(200) <=> Actual(403 Forbidden))
excon.error.response
  :body          => "<?xml version='1.0' encoding='UTF-8'?><Error><Code>InvalidSecurity</Code><Message>The provided security credentials are not valid.</Message><Details>Request was not signed or contained a malformed signature</Details></Error>"
  :cookies       => [
  ]
  :headers       => {
    "Alt-Svc"              => "quic=\":443\"; ma=2592000; v=\"46,43,39\""
    "Cache-Control"        => "private, max-age=0"
    "Content-Length"       => "224"
    "Content-Type"         => "application/xml; charset=UTF-8"
    "Date"                 => "Mon, 23 Sep 2019 20:15:34 GMT"
    "Expires"              => "Mon, 23 Sep 2019 20:15:34 GMT"
    "Server"               => "UploadServer"
    "X-GUploader-UploadID" => "[redacted]"
  }
  :host          => "[redacted]"
  :local_address => "192.168.1.71"
  :local_port    => 52246
  :path          => "/"
  :port          => 443
  :reason_phrase => "Forbidden"
  :remote_ip     => "216.58.193.208"
  :status        => 403
  :status_line   => "HTTP/1.1 403 Forbidden\r\n"
```

It looks like there's an encoding issue with the % which breaks the auth.

**Comment by Temikus** [comment] 2019-09-28 08:12
I've messed around with this a bit, but it looks somewhat non-trivial.

I thought it would be easy enough to just escape the request options:
```
options.update(options) { |k, v| Fog::Google.escape(v) }
```

The problem is though, that then the `marker:` option doesn't actually work anymore :/

I can confirm this doesn't happen in `JSON` Storage api driver, which is the recommended one.
Can you switch to that? It should be (mostly) a drop in replacement.

If not - let me know and I'll try to dig a bit further.

**Comment by Temikus** [comment] 2020-07-22 01:56
I'll close this out since JSON is now the recommended API to access GCS. Though if anyone is feeling that this is particularly pressing - feel free to reopen and let me know!

**Closed by Temikus** 2020-07-22 01:56 UTC
