### ISSUE TITLE
GCE instance creation issue : Not Found (Google::APIClient::ClientError)

### ISSUE THREAD

**Issue by ruby2001** [fog/fog-google#406] opened 2018-07-23 10:12 UTC
Hi Guys ,

Ruby : ruby 2.0.0p247 (2013-06-27 revision 41674) [x86_64-linux]
Fog : fog (1.37.0)
fog-google : (1.6.0, 1.3.3, 0.5.2, 0.0.7)
google-api-client : (0.23.3, 0.19.8, 0.8.6, 0.8.4)

When tried creating Google Compute Engine instance using below fog API , getting Not Found (Google::APIClient::ClientError) .

gclient=Fog::Compute.new({:provider => 'google',:google_project => @@google_project_name ,:google_client_email => @@gclient_mail,:google_json_key_location => @@google_key})

/home/ubuntu/.rvm/gems/ruby-2.0.0-p247/gems/google-api-client-0.8.6/lib/google/api_client.rb:662:inblock (2 levels) in execute!': Not Found (Google::APIClient::ClientError)
from /home/ubuntu/.rvm/gems/ruby-2.0.0-p247/gems/retriable-1.4.1/lib/retriable/retry.rb:27:in perform' from /home/ubuntu/.rvm/gems/ruby-2.0.0-p247/gems/retriable-1.4.1/lib/retriable.rb:15:inretriable'
from /home/ubuntu/.rvm/gems/ruby-2.0.0-p247/gems/google-api-client-0.8.6/lib/google/api_client.rb:645:in block in execute!' from /home/ubuntu/.rvm/gems/ruby-2.0.0-p247/gems/retriable-1.4.1/lib/retriable/retry.rb:27:inperform'
from /home/ubuntu/.rvm/gems/ruby-2.0.0-p247/gems/retriable-1.4.1/lib/retriable.rb:15:in retriable' from /home/ubuntu/.rvm/gems/ruby-2.0.0-p247/gems/google-api-client-0.8.6/lib/google/api_client.rb:636:inexecute!'
from /home/ubuntu/.rvm/gems/ruby-2.0.0-p247/gems/google-api-client-0.8.6/lib/google/api_client.rb:368:in discovery_document' from /home/ubuntu/.rvm/gems/ruby-2.0.0-p247/gems/google-api-client-0.8.6/lib/google/api_client.rb:413:indiscovered_api'
from /home/ubuntu/.rvm/gems/ruby-2.0.0-p247/gems/fog-google-0.0.7/lib/fog/google/compute.rb:1064:in initialize' from /home/ubuntu/.rvm/gems/ruby-2.0.0-p247/gems/fog-core-1.44.3/lib/fog/core/service.rb:115:innew'
from /home/ubuntu/.rvm/gems/ruby-2.0.0-p247/gems/fog-core-1.44.3/lib/fog/core/service.rb:115:in new' from /home/ubuntu/.rvm/gems/ruby-2.0.0-p247/gems/fog-core-1.44.3/lib/fog/compute.rb:55:innew'
`
Please take a look and help us out on this , this is blocking our instance creation flow . Let me know if any additional details are required .

Thanks ..

**Comment by Temikus** [comment] 2018-07-23 12:11
Looking at the log provided, you're using a very old version of fog-google (0.0.7) so this is probably the `ResourceViews` API issue we had to hotfix due to the API being unexpectedly removed:
https://github.com/fog/fog-google/commit/3ba154554382d9cfe9f29710795ec638be881260

Have you tried using newest (v1.6.0) fog-google? I see you've mentioned it in parentheses but I'm not entirely sure. If so - can you provide a newer stack trace?

Another thing is - you're running a deprecated version of Ruby (2.0.0-p247) - while we do strive to maintain compatibility our CI is running on versions starting 2.3 (the oldest non-deprecated) so we may have missed something. Give me a minute to see if I can reproduce.

**Comment by Temikus** [comment] 2018-07-23 12:22
Yeah, seems like google-api-client no longer has a resolvable version working on ruby-2.1:
```
λ bundle                                                                                                                                   (5)
Fetching gem metadata from https://rubygems.org/........
RubyGems 2.0.3 is not threadsafe, so your gems will be installed one at a time. Upgrade to RubyGems 2.1.0 or higher to enable parallel gem installation.
Fetching rake 12.3.1
Installing rake 12.3.1
Fetching public_suffix 3.0.2
Installing public_suffix 3.0.2
Gem::InstallError: public_suffix requires Ruby version >= 2.1.
An error occurred while installing public_suffix (3.0.2), and Bundler cannot continue.
Make sure that `gem install public_suffix -v '3.0.2' --source 'https://rubygems.org/'` succeeds before bundling.

In Gemfile:
  fog-google was resolved to 1.6.0, which depends on
    google-api-client was resolved to 0.23.0, which depends on
      googleauth was resolved to 0.6.2, which depends on
        signet was resolved to 0.8.1, which depends on
          addressable was resolved to 2.5.2, which depends on
            public_suffix
```
You'll need to bump your ruby version or, otherwise, you can try running on `fog-google` 1.3.X, I'm afraid.

Let me know if you can get a newer version repro with a stack trace and I'll do my best to help you out.

**Comment by Temikus** [comment] 2018-07-24 10:44
@ruby2001 

So, a couple of things:
- With 99% certainty the issue in case1 is the resourceviews API blocking startup. It was hotfixed in fog-google `0.1.2`

- If you use GCP and AWS you still do not need to use the `fog` metagem.
Requiring `fog-aws` and `fog-google` should just work and provide all the interfaces you need. `fog` metagem is there for compatibility and legacy reasons only at this point, see the postinstall section:
https://github.com/fog/fog/blob/bb77eff44f1f9231099f97715affe424f330334d/fog.gemspec#L109

So the quickest way to unblock you would be to require the following gems in your setup: 
- "fog-google", "0.1.2"
- "fog-aws", ">= 0.6.0"
, the latter is equivalent to the fog 1.37 constraint: https://github.com/fog/fog/blob/v1.37.0/fog.gemspec

If I'm missing something - just let me know.

**Comment by ruby2001** [comment] 2018-07-25 13:56
@Temikus  : GCE instance creation flow works fine with fog-google (1.6.0) . Thanks a lot for helping us out  !  👍

**Comment by Temikus** [comment] 2018-07-26 10:37
@ruby2001 Great to hear you're up and running!

**Comment by Temikus** [comment] 2018-07-26 10:38
I'll close this out but if you still have issues - no worries, feel free to reopen!

**Closed by Temikus** 2018-07-26 10:38 UTC
